she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('author/<int:pk>/', views.UserArticlesList.as_view(), name='author'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView
from .views import ViewAccount

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(),name='createAccount'),
    path('view-account/', ViewAccount.as_view(),name='viewAccount'),
]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from email.mime import image
from django.db import models


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image_url = models.CharField(max_length=300, default= "https://picsum.photos/200/300")

    def snippet(self):
        return self.content[:50] + '...'

class Author(models.Model):
    user = models.OneToOneField(get_user_model(),on_delete=models.CASCADE)
    author = user.name

    def get_absolute_url(self):
        return reverse("author", kwargs={'pk':self.pk})

    def __str__(self):
        return self.author.username
        

she_codes_news/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

def __str__(self):
    return self.username


# Create your models here.

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory

class StoryForm(ModelForm):
    
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content', 'image_url']
        widgets = {'pub_date': forms.DateInput(format=('%m/%d/%Y'),attrs={'class':'form-control', 'placeholder':'Select a date','type':'date'}),
        'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title', 'style': 'width: 300px;'}), 
        'content':forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write your story here','style': 'width: 300px;'}),
        }

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']
        
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        createstory = NewsStory.objects.all().order_by('-pub_date')
        context['latest_stories'] = createstory[:4]
        context['all_stories'] = createstory
        return context

class UserArticlesList(generic.ListView):
    form_class = StoryForm
    context_object_name = 'article_list'
    template_name = 'userArticle.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = NewsStory.objects.all()
        return context

    def get_queryset(self):
        author_id = self.kwargs['pk']
        return NewsStory.objects.filter(author = author_id)


class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'


class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

class ViewAccount(CreateView):
    model = CustomUser
    fields = ['username', 'email']
    success_url = reverse_lazy('viewAccount')
    template_name = 'registration/viewAccount.html'

she_codes_news/news/templates/author.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<h1>Author List</h1>
<div>
    {% if author_list %}
    <ul>
        {% for story in author_list %}
            <div>
                <h2>{{ story.title }}</h2>
                <h4>{{ story.author }}</h4>
                <div>
                    <img src="{{ story.story_img }}">
                {{ story.content|linebreaks }}
                </div>
            </div>
        {% endfor %}
    </ul>
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
</div>

{% endblock %}

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}

{% block content %}

<div class = "add-story-container"> 
    <h2>Add Your Story</h2>
    <form id="adding-story" action="{% url 'news:newStory' %}" method="post"> 
        {% csrf_token %}
        <div id="create-title">
            Title: {{ form.title }}
        </div>
        <div id="create-date"> 
            Date: {{ form.pub_date }} 
        </div>
        <div id="create-content"> 
            Content: {{ form.content }} 
        </div>
        <div id="create-image"> 
            Image URL: {{form.image_url }} 
        </div>
        <div id="create-submit">
            <button id="submit" type="submit">Create</button> 
        </div>
    </form>
</div>
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    
    <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>


    <h2>All Stories</h2>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <a href="{% url 'news:author' story.author.id %}"><h4>{{ story.author }}</h4></a>
    <div id="story-content">
        <img src="{{ story.image_url }}">
        {{ story.content|linebreaks }}
    </div>
</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        <img src="{{ story.image_url }}">
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
            <h5>{{ story.snippet }}</h5>
        </div>
    </a>
</div>

she_codes_news/news/templates/userArticle.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<div class = "">
    <h2>Authors & their articles</h2>
    <div id="all-stories">
        {% if article_list %}
        <ul>
            {% for story in article_list %}
                <div class="story-card" id="story-card-{{ position }}">
                <img src="{{ story.image_url }}">
                <div class="story-card-text">    
                    <h3>{{ story.title }}</h3>
                    <h4>{{ story.author }}</h4>
                    <h4>{{ story.pub_date }}</h4>
                    <h5>{{ story.snippet|linebreaks }}</h5>
                    </div>
                </div>
            {% endfor %}
        </ul>
            {% else %}
                <p id="">No stories are available.</p>
            {% endif %}
    </div>
</div>  

{% endblock %}

she_codes_news/templates/base.html
<!doctype html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Jenna Crosland">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            {% include './nav.html' %}
        </header>

        {% block content %}{% endblock %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a id="nav-bar" href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
        <a id="nav-bar1" href="{% url 'users:viewAccount' %}">~ {{ user.username }} ~</a>
        <a id="nav-bar" href="{% url 'news:newStory' %}">Write New Story</a>
        <a id="nav-bar" href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a id="nav-bar" href="{% url 'login' %}">Login</a>
        <a id="nav-bar" href="{% url 'users:createAccount' %}">Create Account</a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}

<div class = "add-user-container">
    <h2>Create Account</h2>
    <form id="adding-user" method="post">
        {% csrf_token %}
        <div id="create-user">
            Username: {{ form.username }}
        </div>
        <div id="create-email"> 
            Email: {{ form.email }} 
        </div>
        <div id="create-password"> 
            Password: {{ form.password1 }} 
        </div>
        <ul id="create-list">
            <li>Your password can't be too similar to your other personal information.</li>
            <li>Your password must contain at least 8 characters.</li>
            <li>Your password can’t be a commonly used password.</li>
            <li>Your password can’t be entirely numeric.</li>
        </ul>
        <div id="create-confirm"> 
            Password confirmation: {{form.password2 }} 
        </div> 
        <div id="create-confirmtext">*Enter the same password as before, for verification.*
        </div>
        <div>
            <button id="submit" type="submit">Create Account</button>
        </div>
    </form>

{% endblock %} 
</div>